### ISSUE TITLE
Inquiry only : How we managed shortcut keys for the application

### ISSUE THREAD

**Issue by ghost** [omridevk/ng-keyboard-shortcuts#17]
Hi @omridevk  - I just want to ask about how we can manage the shortcut key for the whole app.

- Is it per component? 

- I have a parent-child component that has the same shortcut key, how can Isolate the shortcut keys per component?

Thanks a lot 👍  for any response.

**Comment by omridevk** [comment]
@JojiePalahang 
1. When you use the <ng-keyboard-shortcuts> component, it registered the key globally, so if you have two <ng-keyboard-shortcuts> in the same tree, they will override each other ( as long as they are both are not destroyed). 
But when a component that holds an <ng-keyboard-shortcuts> is destroyed, so is the registered key associated with the component is removed from the global registry.
2. Currently, the library does not support binding to the same shortcut, it will only trigger the first regisestered shortcut. **However** In the next release, we will add support for multiple binding for same shortcut.
Please let me know if I answered your inquires and if so may I close this ticket?
Thanks.

**Comment by ghost** [comment]
Thanks - Great yup it's clear now, we can now close this ticket.

**Comment by petterkjeilen** [comment]
Hi @omridevk Any news on support for binding to the same shortcut in multiple components ?

**Comment by omridevk** [comment]
Hi sorry for delay, I have a working local branch with multiple binding support, but I have an issue with making it work while keeping the debounce/throttle works, which is very important since it will a breaking change, if I can't get the debounce/throttle to work.
I am still thinking of a solution for this. 
And again sorry for the delay, I had little time to maintain the library, but soon hopefully I will release a version. 
I will update my trello board and share it with you guys so you can keep track of the progress.
Thanks again for the patience.
