### ISSUE TITLE
Mousetrap

### ISSUE THREAD

**Issue by j2L4e** [omridevk/ng-keyboard-shortcuts#36]
I didn't look through the source, but at least this project's README is clearly a modified version of Mousetrap's (https://github.com/ccampbell/mousetrap). It should be (and might be legally required) stated that this is the case (Apache 2).

Edit: To be fair, it seems to be mainly the part about gmail style sequences that caught my attention. Not saying all of this is just a copy!

**Comment by j2L4e** [comment]
It's just a single sentence that was copied. I totally misjudged this. Please bear with me.

**Comment by omridevk** [comment]
@j2L4e 
No problem :) I agree, I have copied that specific line from mousetrap, since it just fun as I am a fan of Konami games (not the corp).
But I can assure that the rest of the library was not copied from Mousetrap in any way whatsoever. I was inspired and learned some stuff from their source code.
